<a href="https://colab.research.google.com/github/nitindavegit/AI-Powered-Regulatory-Compliance-Checker-for-Contracts/blob/main/Week_1_Python_Task.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#  **Python Interview Preparation Guide**
### *All Important Concepts Frequently Asked in Technical Interviews*
**Topics Covered:**
1. Data Types & Variables
2. Strings & String Methods
3. Lists, Tuples, Sets, Dictionaries
4. List Comprehensions
5. Functions, *args, **kwargs
6. Lambda Functions
7. OOP (Classes, Inheritance, Polymorphism)
8. Decorators
9. Generators & Iterators
10. Exception Handling
11. File I/O
12. Modules & Packages
13. Sorting Algorithms
14. Searching Algorithms
15. Data Structures (Stack, Queue, LinkedList)
16. Recursion
17. Multithreading & Multiprocessing
18. Regular Expressions
19. NumPy & Pandas Basics
20. Interview Coding Problems

# ***1. Data Types & Variables***

In [2]:
# Primitive Data Types
Integer = 45
Float = 22.7
Bool = False
Complex = 5 + 6j
String = "Nitin Dave"
none = None

print(type(Integer))
print(type(Float))
print(type(Complex))

print()
print()

# Type Casting
a = int('10')       # str -> int
b = float(56)       # int -> float
c = str(568)        # int -> str

print(a,b,c)

<class 'int'>
<class 'float'>
<class 'complex'>


10 56.0 568


###  Mutable vs Immutable



*   **Immutable: int, float, str, tuple, frozenset**
*   **Mutable:   list, dict, set**



# ***2. Strings & String Methods***



In [21]:
s = 'Nitin Dave'

# Common String Methods
print(s.upper())
print(s.lower())
print(s.split())
print(s.replace("Dave","Ghadkari"))
print(s.strip())
print(s.startswith('Nitin'))
print(s.find('ave'))
print(len(s))

print("\n\n\n")

# String Slicing
print(s[1:5])
print(s[::-1])

# f-String Formatting
name = "Nitin"
age = 20
print(f"Name: {name}, Age: {age}")

print("\n\n\n")

# String is iterable
for char in 'nitin':
  print(char, end=' ')

print("\n\n\n")
# Interview Q: Check if a string is palindrome
def pallindrome(str):
  formatted_str = str.strip().lower()
  reverse_str = formatted_str[::-1]
  if reverse_str == formatted_str:
    return "Pallindrome"
  return "Not a Pallindrome"

print(pallindrome('Nitin'))
print(pallindrome("Hello"))

NITIN DAVE
nitin dave
['Nitin', 'Dave']
Nitin Ghadkari
Nitin Dave
True
7
10




itin
evaD nitiN
Name: Nitin, Age: 20




n i t i n 



Pallindrome
Not a Pallindrome


# ***3.  Lists, Tuples, Sets, Dictionaries***

In [32]:
# List
lst = [1,3,4,5,6]
print(lst)
lst.append(9)
print(lst)
lst.insert(1,2)
print(lst)
lst.remove(3)
print(lst)
lst.pop()
print(lst)
lst.sort()
print(lst)
lst.reverse()
print(lst)

print("\n\n\n")


# Tuple
tup = (1,2,3)
print(tup.count(3))
print(tup.index(1))
a,b,c = tup
print(a,b,c)

print("\n\n\n")

# Set
s1 = {1,4,5}
s2 = {2,4,6}
print(s1.union(s2))
print(s1.intersection(s2))
print(s1.difference(s2))
s1.add(8)
s1.discard(1)
print(s1)


# Dictionary
d = {
    "name": "Nitin",
    "age": 20,
    'city': 'Surat'
}

print(d['name'])
print(d.get('age',0))
d['email'] = 'nitin@gmail.com'
print(d)
del d['city']
print(d.keys(), d.values(), d.items(), end='\n\n')

# Dict Comprehension
squares = {x: x**2 for x in range(1,6)}
print(squares)



[1, 3, 4, 5, 6]
[1, 3, 4, 5, 6, 9]
[1, 2, 3, 4, 5, 6, 9]
[1, 2, 4, 5, 6, 9]
[1, 2, 4, 5, 6]
[1, 2, 4, 5, 6]
[6, 5, 4, 2, 1]




1
0
1 2 3




{1, 2, 4, 5, 6}
{4}
{1, 5}
{8, 4, 5}
Nitin
20
{'name': 'Nitin', 'age': 20, 'city': 'Surat', 'email': 'nitin@gmail.com'}
dict_keys(['name', 'age', 'email']) dict_values(['Nitin', 20, 'nitin@gmail.com']) dict_items([('name', 'Nitin'), ('age', 20), ('email', 'nitin@gmail.com')])

{1: 1, 2: 4, 3: 9, 4: 16, 5: 25}


# ***4. List Comprehensions***

In [34]:
squares = [x**2 for x in range(1,6) ]
print(squares)

# With condition
evens = [x for x in range(1, 21) if x % 2 == 0]
print(evens)


[1, 4, 9, 16, 25]
[2, 4, 6, 8, 10, 12, 14, 16, 18, 20]


# ***5. Functions, ```*args```, ```**kwargs```***





In [38]:
# Basic function

def greet(name, greeting='Hello'):
  return f"{greeting}, {name}"

print(greet("Nitin","Hey"))
print(greet("Jay"))

# *args
def sum_all(*args):
  return sum(args)

print(sum_all(1,2,3,4,5,6))

# **kwargs
def show_info(**kwargs):
  for key, value in kwargs.items():
    print(f"key: {key}, value: {value}")

show_info(name='Nitin', age=20, city='Surat')

Hey, Nitin
Hello, Jay
21
key: name, value: Nitin
key: age, value: 20
key: city, value: Surat


# ***6. Loops***

In [42]:
for char in 'Nitin Dave':
  print(char,end=' ')
print()

count = 0
while(count < 3):
  print("less than 3")
  count += 1

N i t i n   D a v e 
less than 3
less than 3
less than 3


# ***7. Lambda and Map***

In [45]:
# Lambda
cube = lambda x: x**3
print(cube(5))

# Map
nums = [1,2,3,4,5]
square = list(map(lambda x : x**2, nums))
print(square)

125
[1, 4, 9, 16, 25]


# ***8. OOP (Object Oriented Programming)***

In [54]:
# class and object

class Animal:
  species = 'Animal'

  def __init__(self, name, age):
    self.name = name
    self.age = age

  def speak(self):
    return f'{self.name} makes a sound'

  def __str__(self):
    return f'Animal({self.name}, {self.age})'

  def __repr__(self):
    return f'Animal(name={self.name!r}, age={self.age!r})'


a = Animal('Generic',3)
print(a.__str__())
print(a.__repr__())


# Inheritance
class Dog(Animal):
  def __init__(self, name, age, breed):
    super().__init__(name, age)
    self.breed = breed

  def speak(self):     # Method Overriding
    return f"{self.name} says Wooo Wooo"

class Cat(Animal):
  def speak(self):     # Method Overriding
    return f"{self.name} says Meow Meow!"


dog = Dog('Bruno',5,'Pomerian')
cat = Cat('whiskiers',3)

print(dog.speak())
print(cat.speak())


# Polymorphism
animals = [dog, cat, Animal('Bird', 2)]
for animal in animals:
    print(animal.speak())  # Same method, different behavior


# Encapsulation
class BankAccount:
    def __init__(self, balance):
        self.__balance = balance  # Private attribute

    def deposit(self, amount):
        if amount > 0:
            self.__balance += amount

    def get_balance(self):
        return self.__balance

acc = BankAccount(1000)
acc.deposit(500)
print(acc.get_balance())  # 1500


# Abstraction
from abc import ABC, abstractmethod

class Shape(ABC):
    @abstractmethod
    def area(self):
        pass

class Circle(Shape):
    def __init__(self, radius):
        self.radius = radius
    def area(self):
        return 3.14159 * self.radius ** 2

class Rectangle(Shape):
    def __init__(self, w, h):
        self.w, self.h = w, h
    def area(self):
        return self.w * self.h

for shape in [Circle(5), Rectangle(4, 6)]:
    print(f'Area: {shape.area()}')

Animal(Generic, 3)
Animal(name='Generic', age=3)
Bruno says Wooo Wooo
whiskiers says Meow Meow!
Bruno says Wooo Wooo
whiskiers says Meow Meow!
Bird makes a sound
1500
Area: 78.53975
Area: 24


# ***9. Exception Handling***

In [55]:
# Basic try-except
try:
    result = 10 / 0
except ZeroDivisionError as e:
    print(f'Error: {e}')
except (TypeError, ValueError) as e:
    print(f'Type/Value Error: {e}')
else:
    print('No exception occurred!')
finally:
    print('This always runs')



Error: division by zero
This always runs


# ***10. Numpy Basics***

In [61]:
import numpy as np
# Array Creation

arr = np.array([1,2,3,4,5])
zeros = np.zeros((2,2))
ones = np.ones((2,3))
identity = np.eye(2)
arange = np.arange(2,7,1)
linspace = np.linspace(0,1,5)

print('Array:', arr)
print('Arange:', arange)
print('Linspace:', linspace, end='\n\n\n')

# Array properties
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print('Shape:', arr_2d.shape)
print('Dtype:', arr_2d.dtype)
print('Size:', arr_2d.size)
print('Ndim:', arr_2d.ndim, end='\n\n\n')

# Operations
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print('Add:', a + b)
print('Multiply:', a * b)
print('Dot Product:', np.dot(a, b), end='\n\n\n')

# Statistics
data = np.array([10, 20, 30, 40, 50])
print('Mean:', np.mean(data))
print('Std:', np.std(data))
print('Min/Max:', np.min(data), np.max(data), end='\n\n\n')

# Indexing & Slicing
m = np.arange(1, 10).reshape(3, 3)
print(m)
print('Row 0:', m[0])
print('Col 1:', m[:, 1])
print('Submatrix:', m[0:2, 0:2], end='\n\n\n')

Array: [1 2 3 4 5]
Arange: [2 3 4 5 6]
Linspace: [0.   0.25 0.5  0.75 1.  ]


Shape: (2, 3)
Dtype: int64
Size: 6
Ndim: 2


Add: [5 7 9]
Multiply: [ 4 10 18]
Dot Product: 32


Mean: 30.0
Std: 14.142135623730951
Min/Max: 10 50


[[1 2 3]
 [4 5 6]
 [7 8 9]]
Row 0: [1 2 3]
Col 1: [2 5 8]
Submatrix: [[1 2]
 [4 5]]


